# INDUSTRY_TICKERS = {
#     "Thép": ['BVG','TTS','DTL','CBI','VDT','VGS','TMG','VGL','HLA','BCA','TVN','HPG','HMC','HMG','HSG','ITQ','KMT','KVC','MEL','MHL','POM','NKG','KKC','SMC','SHA','SSM','TDS','PAS','SHI','VCA','TTH','TLH','TNA','TNB','TNS','TNI','GDA','KTL','HSV','DFC','TIS'],
#     "Ngân hàng": ['VCB','BID','CTG','TCB','MBB','VPB','ACB','HDB','STB','SHB','EIB','LPB','VIB','MSB','OCB','TPB','SSB','NAB','BAB','KLB'],
#     "Bất động sản": ['VHM','VIC','NVL','PDR','DXG','DIG','KDH','NLG','CEO','HDC','HDG','SCR','TCH','IJC','AGG','CRE','DRH','QCG','SJS','NTL'],
#     "Chứng khoán": ['SSI','VND','VCI','HCM','MBS','FTS','CTS','BSI','VDS','ORS','AGR','APG','SHS','BVS','TVS','VIX'],
#     "Dầu khí": ['GAS','PLX','PVD','PVS','PVC','PVB','BSR','OIL','PVT','CNG','PSH','PXS','PET'],
#     "Bán lẻ": ['MWG','FRT','DGW','PNJ','PET','PSD','HAX','COM','SVC','AST'],
#     "Công nghệ": ['FPT','CMG','ELC','ITD','ICT','SAM','VGI','CTR','FOX'],
#     "Thực phẩm - Đồ uống": ['VNM','SAB','MSN','MCH','KDC','DBC','BAF','PAN','VHC','ANV','IDI','HAG','SBT','QNS','NAF'],
# }

# ----------- Final -------------------
INDUSTRY_TICKERS = {
    "Thép": ['BVG','TTS','DTL','CBI','VDT','VGS','TMG','VGL','HLA','BCA','TVN','HPG','HMC','HMG','HSG','ITQ','KMT','KVC','MEL','MHL','POM','NKG','KKC','SMC','SHA','SSM','TDS','PAS','SHI','VCA','TTH','TLH','TNA','TNB','TNS','TNI','GDA','KTL','HSV','DFC','TIS'],
    "Bán buôn": ['CMC', 'DGW', 'FID', 'GEL', 'HHS', 'HMC', 'HTL', 'JVC', 'KDM', 'KMT', 'MCF', 'MEL', 'NO1', 'PCT', 'PET', 'PIT', 'PLX', 'PMG', 'PPT', 'PPY', 'PSC', 'PSD', 'PSE', 'PTX', 'SDA', 'SHN', 'SMA', 'SMC', 'SRA', 'ST8', 'TDG', 'THS', 'TLH', 'TNI', 'TSC', 'TTH', 'UNI', 'VCM', 'VFG', 'VID', 'VMD', 'VPG', 'VTV', 'VVS'],
    "Bán lẻ": ['BTT', 'CCI', 'CMV', 'COM', 'CTF', 'FRT', 'GMA', 'HAX', 'HTC', 'MWG', 'PNC', 'PNJ', 'SFC', 'SVC', 'TMC'],
    "Bảo hiểm": ['BIC', 'BMI', 'BVH', 'MIG', 'PGI', 'PRE', 'PTI', 'PVI', 'VNR'],
    "Bất động sản": ['AAV', 'AGG', 'API', 'BAX', 'BCE', 'BCM', 'CCL', 'CDC', 'CEO', 'CIG', 'CKG', 'CRE', 'CRV', 'CSC', 'D11', 'D2D', 'DIG', 'DRH', 'DTA', 'DTD', 'DXG', 'DXS', 'EVG', 'FDC', 'FIR', 'HAR', 'HDC', 'HDG', 'HLD', 'HPX', 'HQC', 'HU1', 'ICG', 'IDJ', 'IDV', 'IJC', 'ITC', 'KBC', 'KDH', 'KHG', 'KOS', 'KSF', 'L14', 'LDG', 'LGL', 'LHG', 'NBB', 'NDN', 'NHA', 'NLG', 'NRC', 'NTC', 'NTL', 'NVL', 'PDR', 'PTL', 'PV2', 'QCG', 'RCL', 'SCR', 'SDU', 'SGR', 'SJS', 'SZB', 'SZC', 'SZL', 'TAL', 'TCH', 'TDC', 'TDH', 'TIG', 'TIP', 'TIX', 'TN1', 'V21', 'VC3', 'VC7', 'VHM', 'VIC', 'VPH', 'VPI', 'VRC', 'VRE', 'VTJ'],
    "Chăm sóc sức khỏe": ['DBD', 'DBT', 'DCL', 'DHG', 'DHT', 'DMC', 'DP3', 'DTG', 'DVM', 'FIT', 'IMP', 'LDP', 'MED', 'MKV', 'OPC', 'PMC', 'PPP', 'SPM', 'TNH', 'TRA', 'VDP'],
    "Chế biến Thủy sản": ['AAM', 'ABT', 'ACL', 'ANV', 'ASM', 'CAN', 'CMX', 'DAT', 'FMC', 'IDI', 'KHS', 'SJ1', 'TFC', 'VHC'],
    "Chứng khoán": ['AGR', 'APG', 'APS', 'BSI', 'BVS', 'CTS', 'DSC', 'DSE', 'EVS', 'FTS', 'HBS', 'HCM', 'IVS', 'MBS', 'ORS', 'PSI', 'SHS', 'SSI', 'TCI', 'TCX', 'TVB', 'TVS', 'VCI', 'VCK', 'VDS', 'VFS', 'VIG', 'VIX', 'VND', 'VPX', 'WSS'],
    "Công nghệ và thông tin": ['ABR', 'ADC', 'BED', 'CKV', 'CMG', 'CTR', 'DAD', 'DAE', 'DST', 'EBS', 'ECI', 'EID', 'ELC', 'FPT', 'GLT', 'HEV', 'ICT', 'ITD', 'KST', 'LBE', 'ONE', 'PIA', 'QST', 'SED', 'SGD', 'SGT', 'SMN', 'STC', 'VTC'],
    "Dịch vụ lưu trú, ăn uống, giải trí": ['DAH', 'DSN', 'NVT', 'OCH', 'SGH', 'TTT', 'VNG', 'VPL'],
    "Dịch vụ tư vấn, hỗ trợ": ['INC', 'PPE', 'SDC', 'TV2', 'TV3', 'TV4', 'VNC'],
    "Khai khoáng": ['AMC', 'BKC', 'BMC', 'C32', 'CLM', 'CST', 'DHA', 'DHM', 'HGM', 'HLC', 'HMR', 'KSB', 'KSV', 'MDC', 'MDG', 'MIC', 'MVB', 'NBC', 'NNC', 'PVB', 'PVC', 'PVD', 'PVS', 'TD6', 'THT', 'TMB', 'TNT', 'TVD'],
    "Ngân hàng": ['ACB', 'BAB', 'BID', 'CTG', 'EIB', 'EVF', 'HDB', 'KLB', 'LPB', 'MBB', 'MSB', 'NAB', 'NVB', 'OCB', 'SHB', 'SSB', 'STB', 'TCB', 'TPB', 'VAB', 'VCB', 'VIB', 'VPB'],
    "Nông - Lâm - Ngư": ['CTP', 'HAG', 'HKT', 'HPA', 'HSL', 'NSC', 'SSC', 'SVN', 'VIF'],
    "SX Hàng gia dụng": ['AAT', 'ADS', 'EVE', 'GDT', 'GIL', 'HTG', 'KMR', 'MSH', 'NAV', 'RYG', 'SAV', 'SHA', 'STK', 'SVD', 'TCM', 'TDT', 'TET', 'TNG', 'TTF', 'TVT', 'X20'],
    "SX Nhựa - Hóa chất": ['AAA', 'ABS', 'ADP', 'ALT', 'APH', 'BBS', 'BFC', 'BMP', 'BPC', 'BXH', 'CPC', 'CSV', 'DCM', 'DGC', 'DNP', 'DPM', 'DPR', 'DTT', 'GVR', 'HCD', 'HDA', 'HII', 'HRC', 'HVT', 'LAS', 'LIX', 'NET', 'NFC', 'NTP', 'PBP', 'PCE', 'PCH', 'PGN', 'PHR', 'PLP', 'PMB', 'PMP', 'PSW', 'SDG', 'SDN', 'SFG', 'SFN', 'SPC', 'STP', 'TDP', 'TNC', 'TPC', 'TPP', 'TRC', 'VAF', 'VBC', 'VPS', 'VTZ'],
    "SX Phụ trợ": ['ACG', 'AMV', 'BKG', 'BSR', 'CAP', 'CET', 'DHC', 'DLG', 'GTA', 'HAP', 'HHP', 'INN', 'ITQ', 'MCP', 'NHT', 'PLC', 'PMS', 'PTB', 'SBV', 'SHI', 'SMT', 'SSM', 'SVT', 'TLD', 'TLG', 'TMT'],
    "SX Thiết bị, máy móc": ['CJC', 'CTB', 'CTT', 'NAG', 'NHH', 'QHD', 'SBG', 'SHE'],
    "Sản phẩm cao su": ['BRC', 'CSM', 'DRC', 'SRC'],
    "Thiết bị điện": ['DHP', 'DQC', 'GEE', 'GEX', 'KSD', 'MBG', 'PAC', 'PHN', 'POT', 'RAL', 'SAM', 'TSB', 'TYA', 'VTB', 'VTH'],
    "Thực phẩm - Đồ uống": ['AFX', 'ANT', 'BAF', 'BCF', 'BHN', 'BNA', 'DBC', 'HAD', 'HAT', 'HHC', 'KDC', 'KTS', 'LAF', 'LSS', 'MCH', 'MCM', 'MSN', 'NAF', 'PAN', 'SAB', 'SAF', 'SBT', 'SGC', 'SLS', 'SMB', 'THB', 'VCF', 'VDL', 'VHE', 'VNM'],
    "Tiện ích": ['ASP', 'BTP', 'BTW', 'BWE', 'CHP', 'CLW', 'CNG', 'DDG', 'DNC', 'DRL', 'DTK', 'GAS', 'GDW', 'GEG', 'GHC', 'HID', 'HJS', 'HNA', 'IDC', 'KHP', 'NBP', 'NBW', 'NT2', 'NTH', 'PGC', 'PGD', 'PGS', 'PGV', 'PIC', 'POW', 'PPC', 'PVG', 'S4A', 'SBA', 'SEB', 'SHP', 'SIP', 'SJD', 'TBC', 'TDM', 'TDW', 'TMP', 'TTA', 'TTE', 'UIC', 'VPD', 'VSH'],
    "Tài chính khác": ['IPA', 'OGC', 'TVC'],
    "Vận tải - kho bãi": ['ARM', 'ASG', 'AST', 'CAG', 'CCR', 'CDN', 'CIA', 'CLL', 'DL1', 'DS3', 'DVP', 'DXP', 'GIC', 'GMD', 'GSP', 'HAH', 'HCT', 'HMH', 'HTV', 'HVN', 'ILB', 'MAC', 'MAS', 'MHC', 'NAP', 'NCT', 'PDN', 'PDV', 'PGT', 'PJC', 'PJT', 'PRC', 'PTS', 'PVP', 'PVT', 'QNP', 'SCS', 'SFI', 'SGN', 'SKG', 'STG', 'TCL', 'TCO', 'TCT', 'TJC', 'TMS', 'TOT', 'VGP', 'VIP', 'VJC', 'VMS', 'VNF', 'VNL', 'VNS', 'VNT', 'VOS', 'VSA', 'VSC', 'VSM', 'VTO', 'VTP', 'WCS'],
    "Vật liệu xây dựng": ['ACC', 'BCC', 'BTS', 'CLH', 'CRC', 'CVT', 'DTL', 'DXV', 'FCM', 'GKM', 'GMH', 'GMX', 'HCC', 'HOM', 'HPG', 'HSG', 'HT1', 'KKC', 'LBM', 'MCC', 'NHC', 'NKG', 'NSH', 'PDB', 'TCR', 'TEG', 'THG', 'TKU', 'TMX', 'TTC', 'TXM', 'VCA', 'VCS', 'VGC', 'VGS', 'VHL', 'VIT', 'YBM'],
    "Xây dựng": ['AME', 'BCG', 'C47', 'C69', 'CCC', 'CII', 'CMS', 'CTD', 'CTI', 'CX8', 'DC2', 'DC4', 'DIH', 'DPG', 'FCN', 'HAS', 'HHV', 'HTI', 'HTN', 'HUB', 'HUT', 'HVH', 'L10', 'L18', 'L40', 'LCD', 'LCG', 'LGC', 'LHC', 'LIG', 'LM8', 'MCO', 'MST', 'NDX', 'PC1', 'PEN', 'PHC', 'PPS', 'PTC', 'PTD', 'QTC', 'REE', 'S55', 'S99', 'SC5', 'SCG', 'SCI', 'SD5', 'SD9', 'SJE', 'SRF', 'TA9', 'TCD', 'THD', 'TSA', 'TTL', 'V12', 'VC1', 'VC2', 'VC6', 'VC9', 'VCC', 'VCG', 'VE1', 'VE3', 'VE4', 'VMC', 'VNE', 'VSI'],
}